# Generated by Django 3.1 on 2020-08-28 16:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_tickets', models.IntegerField()),
                ('booking_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.user')),
            ],
        ),
    ]
