# Generated by Django 3.1 on 2020-08-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0004_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='no_of_tickets',
            field=models.PositiveIntegerField(),
        ),
    ]
